export const FETCH_PROBLEMS_REQUEST = 'FETCH_PROBLEMS_REQUEST';
export const FETCH_PROBLEMS_SUCCESS = 'FETCH_PROBLEMS_SUCCESS';
export const FETCH_PROBLEMS_FAILURE = 'FETCH_PROBLEMS_FAILURE';

export const CREATE_PROBLEM_REQUEST = 'CREATE_PROBLEM_REQUEST';
export const CREATE_PROBLEM_SUCCESS = 'CREATE_PROBLEM_SUCCESS';
export const CREATE_PROBLEM_FAILURE = 'CREATE_PROBLEM_FAILURE';

export const DELETE_PROBLEM_REQUEST = 'DELETE_PROBLEM_REQUEST';
export const DELETE_PROBLEM_SUCCESS = 'DELETE_PROBLEM_SUCCESS';
export const DELETE_PROBLEM_FAILURE = 'DELETE_PROBLEM_FAILURE';

export const EDIT_PROBLEM_REQUEST = 'EDIT_PROBLEM_REQUEST';
export const EDIT_PROBLEM_SUCCESS = 'EDIT_PROBLEM_SUCCESS';
export const EDIT_PROBLEM_FAILURE = 'EDIT_PROBLEM_FAILURE';

export const GET_PROBLEM_BY_ID_REQUEST = 'GET_PROBLEM_BY_ID_REQUEST';
export const GET_PROBLEM_BY_ID_SUCCESS = 'GET_PROBLEM_BY_ID_SUCCESS';
export const GET_PROBLEM_BY_ID_FAILURE = 'GET_PROBLEM_BY_ID_FAILURE';
