// testcaseConstants.js

// Fetch Test Cases Constants
export const FETCH_TEST_CASES_REQUEST = 'FETCH_TEST_CASES_REQUEST';
export const FETCH_TEST_CASES_SUCCESS = 'FETCH_TEST_CASES_SUCCESS';
export const FETCH_TEST_CASES_FAILURE = 'FETCH_TEST_CASES_FAILURE';

// Create Test Case Constants
export const CREATE_TEST_CASE_REQUEST = 'CREATE_TEST_CASE_REQUEST';
export const CREATE_TEST_CASE_SUCCESS = 'CREATE_TEST_CASE_SUCCESS';
export const CREATE_TEST_CASE_FAILURE = 'CREATE_TEST_CASE_FAILURE';

// Delete Test Case Constants
export const DELETE_TEST_CASE_REQUEST = 'DELETE_TEST_CASE_REQUEST';
export const DELETE_TEST_CASE_SUCCESS = 'DELETE_TEST_CASE_SUCCESS';
export const DELETE_TEST_CASE_FAILURE = 'DELETE_TEST_CASE_FAILURE';

// Run Test Case Constants
export const RUN_TEST_CASE_REQUEST = 'RUN_TEST_CASE_REQUEST';
export const RUN_TEST_CASE_SUCCESS = 'RUN_TEST_CASE_SUCCESS';
export const RUN_TEST_CASE_FAILURE = 'RUN_TEST_CASE_FAILURE';

// Submit Test Case Constants
export const SUBMIT_TEST_CASE_REQUEST = 'SUBMIT_TEST_CASE_REQUEST';
export const SUBMIT_TEST_CASE_SUCCESS = 'SUBMIT_TEST_CASE_SUCCESS';
export const SUBMIT_TEST_CASE_FAILURE = 'SUBMIT_TEST_CASE_FAILURE';
